
#branches:
#  only:
#    - master

skip_tags: true

version: '{branch}-{build}'

os: Visual Studio 2017

before_build:
  nuget restore

configuration: Release
platform: Any CPU

build:
  parallel: true
  verbosity: minimal

deploy:
  release: build$(APPVEYOR_BUILD_NUMBER)
  description: 'Continuous build'
  provider: GitHub
  auth_token:
    secure: P78ZoBG1yAH9cAGEcoHYItaTTRm/FdrDAkzav1IuDh6uy+LiFd1ZSB6IwrUKPPSG
  artifact: BestTest\bin\$(configuration)\BestTest.exe
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
#    appveyor_repo_tag: true        # deploy on tag push only
