
skip_tags: true

version: '{branch}-{build}'

os: Visual Studio 2017

before_build:
  nuget restore
  - cmd: call BestTest\Properties\Version.bat

configuration: Release
platform: Any CPU

build:
  parallel: true
  verbosity: minimal

artifacts:
  - path: BestTest\bin\$(configuration)\BestTest.exe

deploy:
#  release: build$(APPVEYOR_BUILD_NUMBER)
  release: %ProductVersion%
  description: 'Continuous build'
  provider: GitHub
  auth_token:
    secure: P78ZoBG1yAH9cAGEcoHYItaTTRm/FdrDAkzav1IuDh6uy+LiFd1ZSB6IwrUKPPSG
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
#    appveyor_repo_tag: true        # deploy on tag push only
