# WildcardMatch appveyor.yml script

branches:
  only:
    - master

version: '{branch}-{build}'

os: Visual Studio 2017

before_build:
  nuget restore

configuration: Release
platform: Any CPU

build:
  parallel: true
  verbosity: minimal

#deploy:
#  provider: NuGet
#  api_key:
#    secure: rEYnR9JThbc6x8DdCo1K8+fgsGKzjNKzTZsldXFLYMm/tFPC7JWWvuKpVTrDBd+g
#  skip_symbols: false
