
skip_tags: true

version: '{branch}-{build}'

os: Visual Studio 2017

install:
  - cmd: call BestTest\Properties\ProductVersion.bat

before_build:
  nuget restore

configuration: Release
platform: Any CPU

build:
  parallel: true
  verbosity: minimal

artifacts:
  - path: BestTest\bin\$(configuration)\BestTest.exe

deploy:
  release: '%ProductName% %ProductVersion%'
  description: '%ProductDescription%'
  provider: GitHub
  auth_token:
    secure: P78ZoBG1yAH9cAGEcoHYItaTTRm/FdrDAkzav1IuDh6uy+LiFd1ZSB6IwrUKPPSG
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
